# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Slack bot token'
        # Default value if no value is explicitly provided
        default: 'insert the correct bot slack token here'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SLACK_TOKEN: ${{ github.event.inputs.name }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '^1.15' 
    - run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u github.com/slack-go/slack
        go mod init bartok
        go mod tidy
        go build -o bartok
        ./bartok
